## blueprint title
title: Project

## page settings
pages: false
icon: cube
options:
  template: false
  
## file settings
files:
  fields:
    name:
      label: Title
      type: text
    caption:
      label: Caption
      type: textarea
      buttons: false

## page fields
fields:
  title:
    label: Project Title
    type:  text
    width: 3/4 
  year:
    label: Year Created
    type: text
    width: 1/4
  website:
    label: Project URL
    type: url
  occupation:
    label: Occupation
    type: select
    width: 1/3
    options: query
    query:
      fetch: pages
      template: job
      text: '{{title}} at {{employer}}'
      value: '{{title}} at {{employer}}'
  university:
    label: University
    type: select
    options: query
    width: 1/3
    query:
      fetch: pages
      template: university
      text: '{{fieldOfStudy}} at {{title}}'
      value: '{{fieldOfStudy}} at {{title}}'
  other:
    label: Other
    type: text
    width: 1/3
  headline-b:
    type: headline
    label: Project Description
  description:
    label: Description
    type: markdown
  tools:
    label: What tools were used?
    type: tags
    help: "Add software, hardware, and materials..."
  category:
    label: Creative Fields
    type: checkboxes
    options:
      Branding: Branding
      Graphic Design: Graphic Design
      Illustration: Illustration
      Interaction Design: Interaction Design
      Photography: Photography
      Web Design: Web Design
      Advertising: Advertising
      Editorial Design: Editorial Design
      Web Development: Web Development
  published:
    label: Date Published
    type: datetime
    override: true
    default:
      date: now
      time: now
    time:
      interval: 5
      format: 12
    date:
      format: MM-DD-YYYY
    